-- =============================================================================
-- Migration 254 — CERVICAL screening pipeline (mv_cervical_screening)
-- =============================================================================
-- Auto-generated by scaffold/scaffold.py from scaffold/diseases.py
-- (SCREENING dict). DO NOT hand-edit — re-run the scaffolder instead.
--
-- Builds 2 materialized views:
--   mv_cervical_screening           BKK district × abnormal count
--   mv_cervical_screening_region    non-BKK 4-region × abnormal count
--
-- Signal: per-patient `abnormal` (bool) — TRUE iff the screening test
-- result is abnormal. NULL `abnormal` (test not performed) excluded from
-- the denominator. See spec.sql_app1 / sql_portal in diseases.py for
-- the exact boolean expression per disease.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. mv_cervical_screening — BKK district × screening abnormal rate
-- =============================================================================
DROP MATERIALIZED VIEW IF EXISTS public.mv_cervical_screening CASCADE;

CREATE MATERIALIZED VIEW public.mv_cervical_screening AS
WITH
patient_abnormal AS (
  SELECT patient_id, bool_or(abnormal) AS abnormal
  FROM (
    SELECT patient_id, (msd_cervical = 1) AS abnormal
    FROM bma_med.app1_labhealth
    WHERE patient_id IS NOT NULL AND msd_cervical IS NOT NULL
    UNION ALL
    SELECT patient_id, (msd_cervical = 1) AS abnormal
    FROM bma_med.portal_labhealth
    WHERE patient_id IS NOT NULL AND msd_cervical IS NOT NULL
  ) u
  WHERE patient_id IS NOT NULL
  GROUP BY patient_id
),

patient_geo AS (
  SELECT DISTINCT v.patient_id, v.home_district_code AS district_code
  FROM public.mv_visit_resolved v
  WHERE v.is_dedup_kept = TRUE
    AND v.home_district_code IS NOT NULL
    AND v.home_district_code ~ '^10[0-9]{2}$'
),
joined AS (
  SELECT pg.district_code, pg.patient_id, pa.abnormal
  FROM patient_geo pg
  JOIN patient_abnormal pa ON pa.patient_id = pg.patient_id
  WHERE pa.abnormal IS NOT NULL
)
SELECT
  district_code,
  COUNT(*)::bigint                            AS n_total,
  COUNT(*) FILTER (WHERE abnormal)::bigint    AS n_abnormal,
  ROUND(100.0 * COUNT(*) FILTER (WHERE abnormal) / NULLIF(COUNT(*), 0), 2) AS abnormal_pct
FROM joined
GROUP BY district_code
HAVING COUNT(*) >= 5
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_cervical_screening
  ON public.mv_cervical_screening (district_code);

GRANT SELECT ON public.mv_cervical_screening
  TO bma_med_reader, bma_med_clinician, bma_med_loader,
     bma_etl_writer, bma_dba_admin, bma_api_reader;

COMMENT ON MATERIALIZED VIEW public.mv_cervical_screening IS
  'CERVICAL screening abnormal rate per BKK district. n_abnormal/n_total. '
  'k-anon n>=5. Patients with NULL screening result excluded.';

REFRESH MATERIALIZED VIEW public.mv_cervical_screening;

-- =============================================================================
-- 2. mv_cervical_screening_region — non-BKK 4-region (N/NE/S/C)
-- =============================================================================
DROP MATERIALIZED VIEW IF EXISTS public.mv_cervical_screening_region CASCADE;

CREATE MATERIALIZED VIEW public.mv_cervical_screening_region AS
WITH
patient_abnormal AS (
  SELECT patient_id, bool_or(abnormal) AS abnormal
  FROM (
    SELECT patient_id, (msd_cervical = 1) AS abnormal
    FROM bma_med.app1_labhealth
    WHERE patient_id IS NOT NULL AND msd_cervical IS NOT NULL
    UNION ALL
    SELECT patient_id, (msd_cervical = 1) AS abnormal
    FROM bma_med.portal_labhealth
    WHERE patient_id IS NOT NULL AND msd_cervical IS NOT NULL
  ) u
  WHERE patient_id IS NOT NULL
  GROUP BY patient_id
),

patient_region AS (
  SELECT DISTINCT v.patient_id,
         CASE
           WHEN LEFT(v.home_district_code, 2)::int BETWEEN 50 AND 58 THEN 'N'
           WHEN LEFT(v.home_district_code, 2)::int BETWEEN 30 AND 49 THEN 'NE'
           WHEN LEFT(v.home_district_code, 2)::int BETWEEN 80 AND 96 THEN 'S'
           WHEN LEFT(v.home_district_code, 2)::int BETWEEN 11 AND 29 THEN 'C'
           WHEN LEFT(v.home_district_code, 2)::int BETWEEN 60 AND 77 THEN 'C'
           ELSE NULL
         END AS region_code
  FROM public.mv_visit_resolved v
  WHERE v.is_dedup_kept = TRUE
    AND v.home_district_code IS NOT NULL
    AND v.home_district_code ~ '^[0-9]{4}$'
),
joined AS (
  SELECT pr.region_code, pr.patient_id, pa.abnormal
  FROM patient_region pr
  JOIN patient_abnormal pa ON pa.patient_id = pr.patient_id
  WHERE pr.region_code IS NOT NULL
    AND pa.abnormal IS NOT NULL
)
SELECT
  region_code,
  CASE region_code
    WHEN 'N'  THEN 'ภาคเหนือ'
    WHEN 'NE' THEN 'ภาคอีสาน'
    WHEN 'S'  THEN 'ภาคใต้'
    WHEN 'C'  THEN 'ภาคกลาง'
  END AS region_name_th,
  COUNT(*)::bigint                            AS n_total,
  COUNT(*) FILTER (WHERE abnormal)::bigint    AS n_abnormal,
  ROUND(100.0 * COUNT(*) FILTER (WHERE abnormal) / NULLIF(COUNT(*), 0), 2) AS abnormal_pct
FROM joined
GROUP BY region_code
HAVING COUNT(*) >= 5
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_cervical_screening_region
  ON public.mv_cervical_screening_region (region_code);

GRANT SELECT ON public.mv_cervical_screening_region
  TO bma_med_reader, bma_med_clinician, bma_med_loader,
     bma_etl_writer, bma_dba_admin, bma_api_reader;

COMMENT ON MATERIALIZED VIEW public.mv_cervical_screening_region IS
  'CERVICAL screening abnormal rate per non-BKK region. Same semantics as '
  'mv_cervical_screening. k-anon n>=5.';

REFRESH MATERIALIZED VIEW public.mv_cervical_screening_region;

COMMIT;

-- =============================================================================
-- END migration 254
-- =============================================================================
