-- =============================================================================
-- Migration 353 — XRAY screening factors (mv_xray_screening_factors)
-- =============================================================================
-- Auto-generated by scaffold/scaffold.py from scaffold/diseases.py
-- (SCREENING dict). DO NOT hand-edit — re-run the scaffolder instead.
--
-- Long-format factor cross-tab for XRAY screening:
--   one row per (scope, scope_id, factor_key, factor_group)
--   - scope: 'city' | 'zone' | 'district'
--   - factors: sex, age_group, smoke, alcohol, excercise
--   - n_abnormal / n_total / abnormal_pct
--
-- Powers the tooltip's "ปัจจัยเด่น" panel for screening diseases —
-- shows demographic / lifestyle factor breakdowns instead of district
-- rows (which cluster around lift=1.0 because every district has a
-- similar abnormal rate citywide).
-- =============================================================================

BEGIN;

DROP MATERIALIZED VIEW IF EXISTS public.mv_xray_screening_factors CASCADE;

CREATE MATERIALIZED VIEW public.mv_xray_screening_factors AS
WITH
patient_abnormal AS (
  SELECT patient_id, bool_or(abnormal) AS abnormal
  FROM (
    SELECT patient_id, (msd_chest = 1) AS abnormal
    FROM bma_med.app1_vitalsignslf
    WHERE patient_id IS NOT NULL AND msd_chest IS NOT NULL
    UNION ALL
    SELECT patient_id, (msd_chest = 1) AS abnormal
    FROM bma_med.portal_vitalsignslf
    WHERE patient_id IS NOT NULL AND msd_chest IS NOT NULL
  ) u
  WHERE patient_id IS NOT NULL
  GROUP BY patient_id
),

-- ── Patient → district + zone ────────────────────────────────────────────
patient_geo AS (
  SELECT DISTINCT v.patient_id,
         v.home_district_code AS dcode,
         v.sex_code,
         v.age_group,
         d.zone_code
  FROM public.mv_visit_resolved v
  LEFT JOIN public.ref_districts d ON d.dcode = v.home_district_code
  WHERE v.is_dedup_kept = TRUE
    AND v.patient_id IS NOT NULL
    AND v.home_district_code ~ '^10[0-9]{2}$'
),

-- ── Lifestyle CTEs (mirror mig 217 — DM factors) ────────────────────────
-- Smoke / alcohol code priority: 2 (current) > 1 (former) > 0 (non) → MAX
smoke_app1 AS (
  SELECT patient_id, MAX(smoke)::int AS smk
  FROM bma_med.app1_vitalsignslf
  WHERE patient_id IS NOT NULL AND smoke IN (0,1,2)
  GROUP BY patient_id
),
smoke_portal AS (
  SELECT patient_id, MAX(smoke::int) AS smk
  FROM bma_med.portal_vitalsignslf
  WHERE patient_id IS NOT NULL AND smoke ~ '^[0-2]$'
  GROUP BY patient_id
),
smoke_all AS (
  SELECT patient_id, MAX(smk) AS smk
  FROM (SELECT * FROM smoke_app1 UNION ALL SELECT * FROM smoke_portal) u
  GROUP BY patient_id
),

alcohol_app1 AS (
  SELECT patient_id, MAX(alcohal)::int AS alc
  FROM bma_med.app1_vitalsignslf
  WHERE patient_id IS NOT NULL AND alcohal IN (0,1,2)
  GROUP BY patient_id
),
alcohol_portal AS (
  SELECT patient_id, MAX(alcohal::int) AS alc
  FROM bma_med.portal_vitalsignslf
  WHERE patient_id IS NOT NULL AND alcohal ~ '^[0-2]$'
  GROUP BY patient_id
),
alcohol_all AS (
  SELECT patient_id, MAX(alc) AS alc
  FROM (SELECT * FROM alcohol_app1 UNION ALL SELECT * FROM alcohol_portal) u
  GROUP BY patient_id
),

-- Excercise: best code = 1 (regular). MIN gives priority to regular.
excercise_app1 AS (
  SELECT patient_id, MIN(excercise)::int AS exc
  FROM bma_med.app1_homehealth
  WHERE patient_id IS NOT NULL AND excercise IN (1,2,3)
  GROUP BY patient_id
),
excercise_portal AS (
  SELECT patient_id, MIN(excercise::int) AS exc
  FROM bma_med.portal_homehealth
  WHERE patient_id IS NOT NULL AND excercise ~ '^[1-3]$'
  GROUP BY patient_id
),
excercise_all AS (
  SELECT patient_id, MIN(exc) AS exc
  FROM (SELECT * FROM excercise_app1 UNION ALL SELECT * FROM excercise_portal) u
  GROUP BY patient_id
),

-- ── Per-patient row (joined demographics + abnormal flag) ───────────────
patient_data AS (
  SELECT pa.patient_id, pa.abnormal,
         pg.dcode, pg.zone_code, pg.sex_code, pg.age_group,
         s.smk, a.alc, e.exc
  FROM patient_abnormal pa
  JOIN patient_geo  pg USING (patient_id)
  LEFT JOIN smoke_all     s USING (patient_id)
  LEFT JOIN alcohol_all   a USING (patient_id)
  LEFT JOIN excercise_all e USING (patient_id)
  WHERE pa.abnormal IS NOT NULL
),

-- ── Long-format factor rows (one row per patient × factor) ──────────────
factor_rows AS (
  -- Sex
  SELECT patient_id, dcode, zone_code, abnormal,
         'sex'::text AS factor_key,
         CASE sex_code WHEN 10 THEN 'male' WHEN 20 THEN 'female' END AS factor_group,
         CASE sex_code WHEN 10 THEN 'ชาย' WHEN 20 THEN 'หญิง' END AS factor_group_th,
         CASE sex_code WHEN 10 THEN 'Male' WHEN 20 THEN 'Female' END AS factor_group_en
  FROM patient_data
  WHERE sex_code IN (10, 20)

  UNION ALL
  -- Age group (already pre-derived in mv_visit_resolved)
  SELECT patient_id, dcode, zone_code, abnormal,
         'age_group',
         age_group,
         CASE age_group
           WHEN '18-29' THEN '18–29 ปี'
           WHEN '30-44' THEN '30–44 ปี'
           WHEN '45-59' THEN '45–59 ปี'
           WHEN '60-74' THEN '60–74 ปี'
           WHEN '75+'   THEN '75 ปีขึ้นไป'
         END,
         CASE age_group
           WHEN '18-29' THEN '18–29 yrs'
           WHEN '30-44' THEN '30–44 yrs'
           WHEN '45-59' THEN '45–59 yrs'
           WHEN '60-74' THEN '60–74 yrs'
           WHEN '75+'   THEN '75+ yrs'
         END
  FROM patient_data
  WHERE age_group IN ('18-29','30-44','45-59','60-74','75+')

  UNION ALL
  -- Smoke
  SELECT patient_id, dcode, zone_code, abnormal,
         'smoke',
         CASE smk WHEN 0 THEN 'non_smoker' WHEN 1 THEN 'former_smoker' WHEN 2 THEN 'current_smoker' END,
         CASE smk WHEN 0 THEN 'ไม่สูบ' WHEN 1 THEN 'เคยสูบ' WHEN 2 THEN 'สูบปัจจุบัน' END,
         CASE smk WHEN 0 THEN 'Non-smoker' WHEN 1 THEN 'Former smoker' WHEN 2 THEN 'Current smoker' END
  FROM patient_data
  WHERE smk IN (0,1,2)

  UNION ALL
  -- Alcohol
  SELECT patient_id, dcode, zone_code, abnormal,
         'alcohol',
         CASE alc WHEN 0 THEN 'non_drinker' WHEN 1 THEN 'former_drinker' WHEN 2 THEN 'current_drinker' END,
         CASE alc WHEN 0 THEN 'ไม่ดื่ม' WHEN 1 THEN 'เคยดื่ม' WHEN 2 THEN 'ดื่มปัจจุบัน' END,
         CASE alc WHEN 0 THEN 'Non-drinker' WHEN 1 THEN 'Former drinker' WHEN 2 THEN 'Current drinker' END
  FROM patient_data
  WHERE alc IN (0,1,2)

  UNION ALL
  -- Excercise
  SELECT patient_id, dcode, zone_code, abnormal,
         'excercise',
         CASE exc WHEN 1 THEN 'regular' WHEN 2 THEN 'sometimes' WHEN 3 THEN 'never' END,
         CASE exc WHEN 1 THEN 'ออกกำลังเป็นประจำ' WHEN 2 THEN 'ออกกำลังเป็นบางครั้ง' WHEN 3 THEN 'ไม่ออกกำลัง' END,
         CASE exc WHEN 1 THEN 'Regular exercise' WHEN 2 THEN 'Sometimes' WHEN 3 THEN 'Never' END
  FROM patient_data
  WHERE exc IN (1,2,3)
)

SELECT scope, scope_id, factor_key, factor_group, factor_group_th, factor_group_en,
       n::bigint                             AS n_total,
       n_abn::bigint                         AS n_abnormal,
       ROUND(100.0 * n_abn / NULLIF(n, 0), 2) AS abnormal_pct
FROM (
  -- City scope
  SELECT 'city'::text AS scope, ''::text AS scope_id,
         factor_key, factor_group, factor_group_th, factor_group_en,
         COUNT(*) AS n, COUNT(*) FILTER (WHERE abnormal) AS n_abn
  FROM factor_rows
  WHERE factor_group IS NOT NULL
  GROUP BY factor_key, factor_group, factor_group_th, factor_group_en
  HAVING COUNT(*) >= 5

  UNION ALL
  -- Zone scope
  SELECT 'zone', zone_code,
         factor_key, factor_group, factor_group_th, factor_group_en,
         COUNT(*), COUNT(*) FILTER (WHERE abnormal)
  FROM factor_rows
  WHERE factor_group IS NOT NULL AND zone_code IS NOT NULL
  GROUP BY zone_code, factor_key, factor_group, factor_group_th, factor_group_en
  HAVING COUNT(*) >= 5

  UNION ALL
  -- District scope
  SELECT 'district', dcode,
         factor_key, factor_group, factor_group_th, factor_group_en,
         COUNT(*), COUNT(*) FILTER (WHERE abnormal)
  FROM factor_rows
  WHERE factor_group IS NOT NULL AND dcode ~ '^10[0-9]{2}$'
  GROUP BY dcode, factor_key, factor_group, factor_group_th, factor_group_en
  HAVING COUNT(*) >= 5
) u
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_xray_screening_factors
  ON public.mv_xray_screening_factors (scope, scope_id, factor_key, factor_group);
CREATE INDEX idx_mv_xray_screening_factors_scope
  ON public.mv_xray_screening_factors (scope, scope_id);

GRANT SELECT ON public.mv_xray_screening_factors
  TO bma_med_reader, bma_med_clinician, bma_med_loader,
     bma_etl_writer, bma_dba_admin, bma_api_reader;

COMMENT ON MATERIALIZED VIEW public.mv_xray_screening_factors IS
  'XRAY screening abnormal-rate cross-tab by demographic / lifestyle '
  'factor at city / zone / district scope. Long-format. '
  'k-anon: cells with n<5 dropped at MV build.';

REFRESH MATERIALIZED VIEW public.mv_xray_screening_factors;

COMMIT;

-- =============================================================================
-- END migration 353
-- =============================================================================
