-- =============================================================================
-- 500_revoke_pid_pii.sql — close the API's read window on raw patient identifiers
-- =============================================================================
-- WHY: bma_med.patient.pid_encoded historically held base64-encoded plaintext
-- Thai national IDs (decode is one line of Python). Same problem in every visit
-- table that has a `pid TEXT` column (app1_*, portal_*, app2_app2 — 13 tables).
-- The application API runs as `api_user`, which currently has full table-level
-- SELECT on bma_med.patient (granted in migrations/400_compat_raw_views.sql:317)
-- so any future query against the column would leak the raw IDCARD.
--
-- This migration is the *fast* mitigation:
--   * REVOKE column-level SELECT on the identifier columns from api_user.
--   * Verify with information_schema that the revoke landed.
--
-- It does NOT re-hash existing data — that's 501_rehash_pid_encoded.sql, which
-- needs the IDCARD_HASH_SECRET env var available to psql via :secret.
--
-- This file is idempotent: re-running it is a no-op if the grants are already
-- gone. Safe to apply during traffic; takes < 1 s on a 600k-row patient table.
-- =============================================================================

BEGIN;

-- 1. Patient master — strip column-level SELECT on the identifier columns.
--    Only `bma_med_clinician` and `bma_med_admin` keep read access (per
--    schema_init.sql §"Grants" — same minus pid_encoded).
REVOKE SELECT (pid_encoded, pid_hash) ON bma_med.patient FROM api_user;
REVOKE SELECT (pid_encoded, pid_hash) ON bma_med.patient FROM PUBLIC;

-- 2. Visit tables — every one of these has a `pid TEXT` column generated by
--    /Users/dev/bma-med/generate_table_ddl.py (line 84). Even after the ETL
--    fix, historic rows still hold base64 plaintext until 501 runs. Block read
--    access from api_user as defense-in-depth.
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN
        SELECT table_name
        FROM information_schema.columns
        WHERE table_schema = 'bma_med'
          AND column_name = 'pid'
    LOOP
        EXECUTE format('REVOKE SELECT (pid) ON bma_med.%I FROM api_user', t);
        EXECUTE format('REVOKE SELECT (pid) ON bma_med.%I FROM PUBLIC',  t);
    END LOOP;
END $$;

-- 3. Verify — fail the migration if api_user still has SELECT on pid_encoded.
DO $$
DECLARE
    leaked int;
BEGIN
    SELECT COUNT(*) INTO leaked
    FROM information_schema.column_privileges
    WHERE grantee = 'api_user'
      AND table_schema = 'bma_med'
      AND column_name IN ('pid', 'pid_encoded', 'pid_hash')
      AND privilege_type = 'SELECT';
    IF leaked > 0 THEN
        RAISE EXCEPTION
            'REVOKE failed: api_user still has SELECT on % identifier column(s)',
            leaked;
    END IF;
END $$;

COMMIT;
