"""TS hooks generator — emits 3 React Query hooks per disease.

Generated files (relative to frontend/src/hooks/):
  useXClassification.ts   — /api/v2/<key>/classification
  useXFactors.ts          — /api/v2/<key>/factors
  useXFactorsBulk.ts      — /api/v2/<key>/factors/bulk
"""
from __future__ import annotations

from ..diseases import DiseaseSpec


def _capitalize(s: str) -> str:
    """Convert snake_case-ish key to TitleCase. 'dm' -> 'Dm', 'cvd' -> 'Cvd'."""
    return s[:1].upper() + s[1:]


def gen_classification_hook(spec: DiseaseSpec) -> str:
    k = spec.key
    K = spec.short_upper
    Title = _capitalize(k)
    c4_field = f"c4_{spec.lab.name.replace('_high', '')}"
    return f'''\'use client\'

import {{ useQuery, type UseQueryResult }} from \'@tanstack/react-query\'

/** API contract from /api/v2/{k}/classification. Auto-generated — do not hand-edit. */
export interface {Title}Classification {{
  scope: \'city\' | \'zone\' | \'district\' | \'non_bkk\'
  scope_id: string | null
  total_patients: number
  totals: {{
    c1_risk: number
    c2_diag: number
    c3_family: number
    {c4_field}: number
  }}
  wilson_ci: Record<
    \'c1_risk\' | \'c2_diag\' | \'c3_family\' | \'{c4_field}\',
    {{ p: number; lower: number; upper: number }}
  >
  patterns: {{ pattern: string; n: number; pct: number }}[]
  named_groups: {{
    /** UNION of c1/c2/c4 (family excluded) — patients with at least 1 active {K} signal. */
    any_{k}_signal: number
    /** Strict newly-found in screening: self-reported NOT-{K} but lab+. */
    newly_found_{k}: number
  }}
  districts?: {Title}DistrictBreakdown[]
}}

export interface {Title}DistrictBreakdown {{
  district_code: string
  district_name: string | null
  zone_code: string | null
  total: number
  totals: {{
    c1_risk: number
    c2_diag: number
    c3_family: number
    {c4_field}: number
  }}
  named_groups: {{
    any_{k}_signal: number
    newly_found_{k}: number
  }}
}}

export function use{Title}Classification(
  scope: \'city\' | \'zone\' | \'district\' | \'non_bkk\',
  id?: string,
  opts?: {{ enabled?: boolean }},
): UseQueryResult<{Title}Classification> {{
  return useQuery<{Title}Classification>({{
    queryKey: [\'v2\', \'{k}/classification\', scope, id ?? null],
    queryFn: async () => {{
      const qs = `{k}/classification?scope=${{scope}}${{id ? `&id=${{id}}` : \'\'}}`
      const res = await fetch(`/api/v2/${{qs}}`)
      if (!res.ok) throw new Error(`HTTP ${{res.status}}`)
      const json = await res.json()
      return (json.data ?? json) as {Title}Classification
    }},
    staleTime: 5 * 60_000,
    enabled: opts?.enabled,
    retry: 1,
  }})
}}
'''


def gen_factors_hook(spec: DiseaseSpec) -> str:
    k = spec.key
    K = spec.short_upper
    Title = _capitalize(k)
    return f'''\'use client\'

import {{ useQuery, type UseQueryResult }} from \'@tanstack/react-query\'

/** /api/v2/{k}/factors — auto-generated by scaffold/scaffold.py. */
export interface {Title}FactorGroup {{
  group: string
  label_th: string
  label_en: string
  n: number
  {k}_n: number
  {k}_pct: number
  /** {k}_pct / scope_baseline_pct — <1 protective, >1 elevated. */
  lift: number
}}

export interface {Title}Factor {{
  factor_key: \'bmi_cat\' | \'smoke\' | \'alcohol\' | \'age_group\' | \'excercise\' | \'family_{k}\'
  factor_label_th: string
  factor_label_en: string
  groups: {Title}FactorGroup[]
  top_group: string | null
}}

export interface {Title}FactorsResponse {{
  scope: \'zone\' | \'city\' | \'district\' | \'non_bkk\'
  scope_id: string | null
  zone_{k}_pct: number
  factors: {Title}Factor[]
}}

export function use{Title}Factors(
  scope: \'city\' | \'zone\' | \'district\' | \'non_bkk\',
  id?: string,
  opts?: {{ enabled?: boolean }},
): UseQueryResult<{Title}FactorsResponse> {{
  return useQuery<{Title}FactorsResponse>({{
    queryKey: [\'v2\', \'{k}/factors\', scope, id ?? null],
    queryFn: async () => {{
      const qs = `{k}/factors?scope=${{scope}}${{id ? `&id=${{id}}` : \'\'}}`
      const res = await fetch(`/api/v2/${{qs}}`)
      if (!res.ok) throw new Error(`HTTP ${{res.status}}`)
      const json = await res.json()
      return (json.data ?? json) as {Title}FactorsResponse
    }},
    staleTime: 5 * 60_000,
    enabled: opts?.enabled,
    retry: 1,
  }})
}}
'''


def gen_factors_bulk_hook(spec: DiseaseSpec) -> str:
    k = spec.key
    Title = _capitalize(k)
    return f'''\'use client\'

import {{ useQuery, type UseQueryResult }} from \'@tanstack/react-query\'
import type {{ {Title}FactorsResponse }} from \'./use{Title}Factors\'

/**
 * One-shot bulk payload for the map tooltip layer — city + every zone +
 * every BKK district + non_bkk in a single HTTP round-trip. Auto-generated.
 */
export interface {Title}FactorsBulk {{
  city: {Title}FactorsResponse
  zones: Record<string, {Title}FactorsResponse>
  districts: Record<string, {Title}FactorsResponse>
  non_bkk: {Title}FactorsResponse
}}

export function use{Title}FactorsBulk(
  opts?: {{ enabled?: boolean }},
): UseQueryResult<{Title}FactorsBulk> {{
  return useQuery<{Title}FactorsBulk>({{
    queryKey: [\'v2\', \'{k}/factors/bulk\'],
    queryFn: async () => {{
      const res = await fetch(\'/api/v2/{k}/factors/bulk\')
      if (!res.ok) throw new Error(`HTTP ${{res.status}}`)
      const json = await res.json()
      return (json.data ?? json) as {Title}FactorsBulk
    }},
    staleTime: 10 * 60_000,
    enabled: opts?.enabled,
    retry: 1,
  }})
}}
'''


def gen_all_hooks(spec: DiseaseSpec) -> dict[str, str]:
    """Returns {filename: content} for the 3 hook files."""
    Title = _capitalize(spec.key)
    return {
        f"use{Title}Classification.ts": gen_classification_hook(spec),
        f"use{Title}Factors.ts":        gen_factors_hook(spec),
        f"use{Title}FactorsBulk.ts":    gen_factors_bulk_hook(spec),
    }
