"""FastAPI router generator — emits api/routers/<key>.py from a DiseaseSpec.

The generated router exposes:
  GET /api/v2/<key>/classification  (scope=zone|city|district|non_bkk, optional pattern filter)
  GET /api/v2/<key>/factors          (scope=zone|city|district|non_bkk)
  GET /api/v2/<key>/factors/bulk     (one-shot for the map tooltip layer)

Convention: any_<key>_signal = c1 OR c2 OR c4 (family/c3 excluded).
The pattern bit positions are: pattern[0]=c1, [1]=c2, [2]=c3, [3]=c4.
"""
from __future__ import annotations

from ..diseases import DiseaseSpec


def gen_router(spec: DiseaseSpec) -> str:
    k = spec.key
    K = spec.short_upper
    lab_chip = spec.lab.chip_id
    lab_label_th = spec.lab.chip_label_th
    lab_label_en = spec.lab.chip_label_en
    return f'''"""{K} router — exposes mv_{k}_classification (4-bit pattern) +
mv_{k}_factors{{,_district,_region}} cross-tabs.

Auto-generated by scaffold/scaffold.py from scaffold/diseases.py.
Edit the DiseaseSpec, then re-run the scaffolder. Do NOT hand-edit this file.

Pattern is a 4-char bitstring `c1c2c3c4`:
    c1 = risk     ({K} risk per screening rules)
    c2 = diag     (already self-reported having {K})
    c3 = family   (parent had {K})
    c4 = {spec.lab.name}  ({lab_label_en})

any_{k}_signal = c1 OR c2 OR c4 (family excluded — hereditary risk, not
active disease state). The "ทั้งหมด" chip uses this.
"""
from __future__ import annotations

import re
from typing import Optional

from fastapi import APIRouter, HTTPException, Query

from database import execute_query, execute_scalar
from security import K_ANONYMITY_THRESHOLD
from cache import cache_get, cache_set, TTL_T3_FILTERED
from services.reports.blocks._stats_helpers import wilson_ci

router = APIRouter(prefix="/api/v2/{k}", tags=["{K} Classification"])

_VALID_SCOPES = {{"city", "zone", "district", "non_bkk"}}


def _build_where(scope: str, scope_id: Optional[str]) -> tuple[str, tuple]:
    """Return (where_clause, params) for mv_{k}_classification based on scope."""
    if scope == "city":
        return ("WHERE district_code ~ '^10[0-9]{{2}}$'", ())
    if scope == "zone":
        # Zone -> aggregate the BKK districts in that zone (joined via ref_districts).
        return (
            "WHERE district_code IN (SELECT dcode FROM public.ref_districts WHERE zone_code = %s)",
            (scope_id,),
        )
    if scope == "district":
        return ("WHERE district_code = %s", (scope_id,))
    if scope == "non_bkk":
        return ("WHERE district_code !~ '^10[0-9]{{2}}$' AND district_code ~ '^[0-9]{{4}}$'", ())
    raise HTTPException(status_code=400, detail=f"Invalid scope: {{scope}}")


@router.get("/classification")
def {k}_classification(
    scope: str = Query(..., description="zone | city | district | non_bkk"),
    id: Optional[str] = Query(None, description="zone_code or district_code (required when scope='zone'|'district')"),
    pattern: Optional[str] = Query(None, min_length=4, max_length=4, description="Optional 4-char pattern filter, e.g. '1010'"),
):
    """Aggregated {K} 4-pattern classification + Wilson CIs + named groups."""
    if scope not in _VALID_SCOPES:
        raise HTTPException(status_code=400, detail=f"Invalid scope. Must be one of {{sorted(_VALID_SCOPES)}}")
    if scope not in ("city", "non_bkk") and not id:
        raise HTTPException(status_code=422, detail=f"id required when scope='{{scope}}'")
    if scope == "district" and id and not re.match(r"^10[0-9]{{2}}$", id):
        raise HTTPException(status_code=422, detail="district id must match ^10\\\\d\\\\d$ (BKK)")

    if pattern is not None and any(ch not in "01" for ch in pattern):
        raise HTTPException(status_code=422, detail=f"Invalid pattern '{{pattern}}'")

    scope_id = id if scope not in ("city", "non_bkk") else None
    cache_key = f"{k}:cls:{{scope}}:{{scope_id}}:{{pattern}}"
    cached = cache_get(cache_key)
    if cached is not None:
        return cached

    where, params = _build_where(scope, scope_id)
    extra = ""
    if pattern is not None:
        extra = " AND pattern = %s"
        params = params + (pattern,)
    rows = execute_query(
        f"""
        SELECT pattern, SUM(n_patients)::bigint AS n
        FROM public.mv_{k}_classification
        {{where}}{{extra}}
        GROUP BY pattern
        ORDER BY pattern
        """,
        params or None,
    )

    nf_by_district: dict[str, int] = {{}}
    by_dc: dict[str, dict] = {{}}
    if scope == "city":
        # Per-district breakdown (used by frontend for patterned heatmap)
        dist_rows = execute_query(
            """
            SELECT m.district_code, m.pattern, SUM(m.n_patients)::bigint AS n,
                   d.zone_code, d.name_th
            FROM public.mv_{k}_classification m
            LEFT JOIN public.ref_districts d ON d.dcode = m.district_code
            WHERE m.district_code ~ '^10[0-9]{{2}}$'
            GROUP BY m.district_code, m.pattern, d.zone_code, d.name_th
            ORDER BY m.district_code, m.pattern
            """,
            None,
        )
        for r in dist_rows:
            dc = r["district_code"]
            entry = by_dc.setdefault(dc, {{
                "district_code": dc,
                "district_name": r.get("name_th"),
                "zone_code": r.get("zone_code"),
                "total": 0,
                "totals": {{"c1_risk": 0, "c2_diag": 0, "c3_family": 0, "c4_{spec.lab.name.replace('_high', '')}": 0}},
                "named_groups": {{"any_{k}_signal": 0, "newly_found_{k}": 0}},
            }})
            n = int(r["n"])
            p = r["pattern"]
            entry["total"] += n
            if p[0] == "1": entry["totals"]["c1_risk"] += n
            if p[1] == "1": entry["totals"]["c2_diag"] += n
            if p[2] == "1": entry["totals"]["c3_family"] += n
            if p[3] == "1": entry["totals"]["c4_{spec.lab.name.replace('_high', '')}"] += n
            # any_{k}_signal = c1 OR c2 OR c4 (family/c3 excluded — see scaffold/diseases.py)
            if p[0] == "1" or p[1] == "1" or p[3] == "1":
                entry["named_groups"]["any_{k}_signal"] += n
            # newly_found = c2=0 AND c4=1 (self-reported NO-{K} but lab+).
            # c1 can be anything — the cohort is "previously-undiagnosed lab+".
            if p[1] == "0" and p[3] == "1":
                entry["named_groups"]["newly_found_{k}"] += n

        districts_payload = [
            v for v in by_dc.values() if v["total"] >= K_ANONYMITY_THRESHOLD
        ]
        districts_payload.sort(key=lambda v: v["district_code"])
    else:
        districts_payload = []

    total = sum(int(r["n"]) for r in rows)
    if total < K_ANONYMITY_THRESHOLD:
        raise HTTPException(status_code=404, detail=f"Suppressed: total < {{K_ANONYMITY_THRESHOLD}}")

    c1_risk   = sum(int(r["n"]) for r in rows if r["pattern"][0] == "1")
    c2_diag   = sum(int(r["n"]) for r in rows if r["pattern"][1] == "1")
    c3_family = sum(int(r["n"]) for r in rows if r["pattern"][2] == "1")
    c4_lab    = sum(int(r["n"]) for r in rows if r["pattern"][3] == "1")

    def _ci(k_count: int, n: int) -> dict:
        if n == 0:
            return {{"p": 0.0, "lower": 0.0, "upper": 0.0}}
        lo, hi = wilson_ci(k_count, n)
        return {{"p": round(k_count / n, 4), "lower": round(lo, 4), "upper": round(hi, 4)}}

    # any_{k}_signal: c1 OR c2 OR c4 (family excluded)
    any_signal = sum(int(r["n"]) for r in rows
                     if r["pattern"][0] == "1" or r["pattern"][1] == "1" or r["pattern"][3] == "1")
    # newly_found_{k}: previously-undiagnosed (c2=0) + lab+ (c4=1).
    # c1 (risk) can be anything — what matters is they self-reported NOT having
    # the disease but the lab confirmed it.
    newly_found = sum(int(r["n"]) for r in rows
                      if r["pattern"][1] == "0" and r["pattern"][3] == "1")

    result = {{
        "data": {{
            "scope": scope,
            "scope_id": scope_id,
            "total_patients": total,
            "totals": {{
                "c1_risk":   c1_risk,
                "c2_diag":   c2_diag,
                "c3_family": c3_family,
                "c4_{spec.lab.name.replace('_high', '')}":    c4_lab,
            }},
            "wilson_ci": {{
                "c1_risk":   _ci(c1_risk,   total),
                "c2_diag":   _ci(c2_diag,   total),
                "c3_family": _ci(c3_family, total),
                "c4_{spec.lab.name.replace('_high', '')}":    _ci(c4_lab, total),
            }},
            "patterns": [
                {{"pattern": r["pattern"], "n": int(r["n"]),
                  "pct": round(100 * int(r["n"]) / total, 4) if total else 0.0}}
                for r in rows
            ],
            "named_groups": {{
                "any_{k}_signal":  any_signal,
                "newly_found_{k}": newly_found,
            }},
            "districts": districts_payload,
        }}
    }}

    cache_set(cache_key, result, TTL_T3_FILTERED)
    return result


# ── /factors ────────────────────────────────────────────────────────────

_FACTOR_LABELS: dict[str, dict[str, str]] = {{
    "bmi_cat":      {{"th": "ดัชนีมวลกาย (BMI)",       "en": "BMI category"}},
    "smoke":        {{"th": "การสูบบุหรี่",              "en": "Smoking status"}},
    "alcohol":      {{"th": "การดื่มแอลกอฮอล์",          "en": "Alcohol consumption"}},
    "age_group":    {{"th": "กลุ่มอายุ",                 "en": "Age group"}},
    "excercise":    {{"th": "การออกกำลังกาย",           "en": "Exercise frequency"}},
    "family_{k}":   {{"th": "ประวัติ{spec.chip_disease_word_th}ในครอบครัว", "en": "Family history of {K}"}},
}}

_GROUP_ORDER: dict[str, list[str]] = {{
    "bmi_cat":      ["normal", "overweight", "obese", "severely_obese"],
    "smoke":        ["non_smoker", "former_smoker", "current_smoker"],
    "alcohol":      ["non_drinker", "former_drinker", "current_drinker"],
    "age_group":    ["18-29", "30-44", "45-59", "60-74", "75+"],
    "excercise":    ["regular", "sometimes", "never"],
    "family_{k}":   ["family_no", "family_yes"],
}}


def _shape_factors(rows: list[dict], scope: str, scope_id: Optional[str]) -> dict:
    """Reshape raw MV rows into the canonical factors response."""
    factor_totals: dict[str, tuple[int, int]] = {{}}
    for r in rows:
        fk = r["factor_key"]
        n_acc, hits_acc = factor_totals.get(fk, (0, 0))
        factor_totals[fk] = (n_acc + int(r["n"]), hits_acc + int(r["{k}_n"]))
    if not factor_totals:
        return {{
            "scope": scope, "scope_id": scope_id,
            "zone_{k}_pct": 0.0, "factors": [],
        }}
    baseline_fk = max(factor_totals, key=lambda k_: factor_totals[k_][0])
    base_n, base_hits = factor_totals[baseline_fk]
    zone_pct = round(100.0 * base_hits / base_n, 2) if base_n > 0 else 0.0

    by_factor: dict[str, list[dict]] = {{}}
    for r in rows:
        fk = r["factor_key"]
        n = int(r["n"])
        hits = int(r["{k}_n"])
        pct = round(100.0 * hits / n, 2) if n > 0 else 0.0
        lift = round(pct / zone_pct, 2) if zone_pct > 0 else 0.0
        by_factor.setdefault(fk, []).append({{
            "group":    r["factor_group"],
            "label_th": r["factor_group_th"],
            "label_en": r["factor_group_en"],
            "n":        n,
            "{k}_n":    hits,
            "{k}_pct":  pct,
            "lift":     lift,
        }})

    factors_payload: list[dict] = []
    for fk in _FACTOR_LABELS:
        groups = by_factor.get(fk, [])
        if not groups:
            continue
        order = {{g: i for i, g in enumerate(_GROUP_ORDER.get(fk, []))}}
        groups.sort(key=lambda g: order.get(g["group"], 99))
        eligible = [g for g in groups if g["n"] >= K_ANONYMITY_THRESHOLD]
        top_group = max(eligible, key=lambda g: g["lift"])["group"] if eligible else None
        factors_payload.append({{
            "factor_key":      fk,
            "factor_label_th": _FACTOR_LABELS[fk]["th"],
            "factor_label_en": _FACTOR_LABELS[fk]["en"],
            "groups":          groups,
            "top_group":       top_group,
        }})

    return {{
        "scope": scope, "scope_id": scope_id,
        "zone_{k}_pct": zone_pct,
        "factors": factors_payload,
    }}


@router.get("/factors")
def {k}_factors(
    scope: str = Query(..., description="zone | city | district | non_bkk"),
    id: Optional[str] = Query(None),
):
    if scope not in _VALID_SCOPES:
        raise HTTPException(status_code=400, detail=f"Invalid scope")
    if scope == "zone" and not id:
        raise HTTPException(status_code=422, detail="id required for scope='zone'")
    if scope == "district":
        if not id:
            raise HTTPException(status_code=422, detail="id required for scope='district'")
        if not re.match(r"^10[0-9]{{2}}$", id):
            raise HTTPException(status_code=422, detail="district id must match ^10\\\\d\\\\d$")

    scope_id = id if scope not in ("city", "non_bkk") else None
    cache_key = f"{k}:factors:{{scope}}:{{scope_id}}"
    cached = cache_get(cache_key)
    if cached is not None:
        return cached

    if scope == "zone":
        rows = execute_query(
            """
            SELECT factor_key, factor_group, factor_group_th, factor_group_en,
                   n::bigint AS n, {k}_n::bigint AS {k}_n
            FROM public.mv_{k}_factors
            WHERE zone_code = %s
            """,
            (scope_id,),
        )
    elif scope == "district":
        rows = execute_query(
            """
            SELECT factor_key, factor_group, factor_group_th, factor_group_en,
                   n::bigint AS n, {k}_n::bigint AS {k}_n
            FROM public.mv_{k}_factors_district
            WHERE district_code = %s
            """,
            (scope_id,),
        )
    elif scope == "non_bkk":
        rows = execute_query(
            """
            SELECT factor_key, factor_group,
                   MAX(factor_group_th) AS factor_group_th,
                   MAX(factor_group_en) AS factor_group_en,
                   SUM(n)::bigint     AS n,
                   SUM({k}_n)::bigint AS {k}_n
            FROM public.mv_{k}_factors_region
            GROUP BY factor_key, factor_group
            """,
            None,
        )
    else:  # city
        rows = execute_query(
            """
            SELECT factor_key, factor_group,
                   MAX(factor_group_th) AS factor_group_th,
                   MAX(factor_group_en) AS factor_group_en,
                   SUM(n)::bigint     AS n,
                   SUM({k}_n)::bigint AS {k}_n
            FROM public.mv_{k}_factors
            GROUP BY factor_key, factor_group
            """,
            None,
        )

    if not rows:
        raise HTTPException(status_code=404, detail=f"No rows for scope='{{scope}}', id='{{scope_id}}'")
    result = {{"data": _shape_factors(rows, scope, scope_id)}}
    cache_set(cache_key, result, TTL_T3_FILTERED)
    return result


@router.get("/factors/bulk")
def {k}_factors_bulk():
    """One-shot payload: city + every zone + every BKK district + non_bkk."""
    cache_key = "{k}:factors:bulk"
    cached = cache_get(cache_key)
    if cached is not None:
        return cached

    zone_rows = execute_query(
        """SELECT zone_code, factor_key, factor_group, factor_group_th, factor_group_en,
                  n::bigint AS n, {k}_n::bigint AS {k}_n
           FROM public.mv_{k}_factors""",
        None,
    )
    dist_rows = execute_query(
        """SELECT district_code, factor_key, factor_group, factor_group_th, factor_group_en,
                  n::bigint AS n, {k}_n::bigint AS {k}_n
           FROM public.mv_{k}_factors_district""",
        None,
    )
    non_bkk_rows = execute_query(
        """SELECT factor_key, factor_group,
                  MAX(factor_group_th) AS factor_group_th,
                  MAX(factor_group_en) AS factor_group_en,
                  SUM(n)::bigint     AS n,
                  SUM({k}_n)::bigint AS {k}_n
           FROM public.mv_{k}_factors_region
           GROUP BY factor_key, factor_group""",
        None,
    )

    by_zone: dict[str, list[dict]] = {{}}
    city_acc: dict[tuple[str, str], dict] = {{}}
    for r in zone_rows:
        zc = r["zone_code"]
        by_zone.setdefault(zc, []).append(r)
        key = (r["factor_key"], r["factor_group"])
        agg = city_acc.get(key)
        if agg is None:
            city_acc[key] = {{
                "factor_key":      r["factor_key"],
                "factor_group":    r["factor_group"],
                "factor_group_th": r["factor_group_th"],
                "factor_group_en": r["factor_group_en"],
                "n":               int(r["n"]),
                "{k}_n":           int(r["{k}_n"]),
            }}
        else:
            agg["n"]      += int(r["n"])
            agg["{k}_n"]  += int(r["{k}_n"])
    city_rows = list(city_acc.values())

    by_district: dict[str, list[dict]] = {{}}
    for r in dist_rows:
        by_district.setdefault(r["district_code"], []).append(r)

    zones_payload = {{zc: _shape_factors(rs, "zone", zc) for zc, rs in by_zone.items()}}
    districts_payload = {{dc: _shape_factors(rs, "district", dc) for dc, rs in by_district.items()}}
    city_payload = _shape_factors(city_rows, "city", None)
    non_bkk_payload = _shape_factors(non_bkk_rows, "non_bkk", None)

    result = {{
        "data": {{
            "city":      city_payload,
            "zones":     zones_payload,
            "districts": districts_payload,
            "non_bkk":   non_bkk_payload,
        }}
    }}
    cache_set(cache_key, result, TTL_T3_FILTERED)
    return result
'''
