"""SQL migration generator for screening-only diseases.

Emits ONE materialized view per disease:
  mv_<key>_screening (district_code, n_total, n_abnormal, abnormal_pct)

Plus the same in non-BKK aggregate form (4 regions). Frontend can derive
city/zone aggregates client-side from the per-district payload.

The screening signal comes from the disease's `sql_app1` / `sql_portal`
CTE bodies (see ScreeningSpec). Each must SELECT (patient_id, <bool> AS
abnormal). Rows with NULL `abnormal` are treated as "test not performed"
and excluded from the denominator.

──────────────────────────────────────────────────────────────────────────
NOTE on REFRESH CONCURRENTLY:
The migration uses plain `REFRESH MATERIALIZED VIEW` (non-concurrent),
which takes AccessExclusiveLock. CONCURRENTLY would be safer for online
refreshes — BUT it cannot be used on a freshly-created MV (the first
populating refresh must be non-concurrent per Postgres semantics). Since
the migration drops + recreates each time, the in-migration refresh is
always the first refresh of a fresh MV.

If/when an operational refresher (cron, scheduled job) is added, it can
safely call `REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_<k>_screening`
because the unique index on `district_code` is already in place. Keep the
unique index requirement in mind when generating new MVs.
──────────────────────────────────────────────────────────────────────────
"""
from __future__ import annotations

from ..diseases import ScreeningSpec


def _indent(s: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in s.splitlines())


def _abnormal_cte(spec: ScreeningSpec) -> str:
    """The combined patient_abnormal CTE — bool_or across both sources."""
    if spec.sql_portal.strip():
        body = f"""    {_indent(spec.sql_app1, 4).strip()}
    UNION ALL
    {_indent(spec.sql_portal, 4).strip()}"""
    else:
        body = f"    {_indent(spec.sql_app1, 4).strip()}"
    return f"""patient_abnormal AS (
  SELECT patient_id, bool_or(abnormal) AS abnormal
  FROM (
{body}
  ) u
  WHERE patient_id IS NOT NULL
  GROUP BY patient_id
)"""


def gen_screening_migration(spec: ScreeningSpec) -> str:
    """Full migration SQL: 2 MVs (BKK district + non-BKK region)."""
    k = spec.key
    n = spec.migration_number
    K = spec.short_upper

    return f"""-- =============================================================================
-- Migration {n} — {K} screening pipeline (mv_{k}_screening)
-- =============================================================================
-- Auto-generated by scaffold/scaffold.py from scaffold/diseases.py
-- (SCREENING dict). DO NOT hand-edit — re-run the scaffolder instead.
--
-- Builds 2 materialized views:
--   mv_{k}_screening           BKK district × abnormal count
--   mv_{k}_screening_region    non-BKK 4-region × abnormal count
--
-- Signal: per-patient `abnormal` (bool) — TRUE iff the screening test
-- result is abnormal. NULL `abnormal` (test not performed) excluded from
-- the denominator. See spec.sql_app1 / sql_portal in diseases.py for
-- the exact boolean expression per disease.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. mv_{k}_screening — BKK district × screening abnormal rate
-- =============================================================================
DROP MATERIALIZED VIEW IF EXISTS public.mv_{k}_screening CASCADE;

CREATE MATERIALIZED VIEW public.mv_{k}_screening AS
WITH
{_abnormal_cte(spec)},

patient_geo AS (
  SELECT DISTINCT v.patient_id, v.home_district_code AS district_code
  FROM public.mv_visit_resolved v
  WHERE v.is_dedup_kept = TRUE
    AND v.home_district_code IS NOT NULL
    AND v.home_district_code ~ '^10[0-9]{{2}}$'
),
joined AS (
  SELECT pg.district_code, pg.patient_id, pa.abnormal
  FROM patient_geo pg
  JOIN patient_abnormal pa ON pa.patient_id = pg.patient_id
  WHERE pa.abnormal IS NOT NULL
)
SELECT
  district_code,
  COUNT(*)::bigint                            AS n_total,
  COUNT(*) FILTER (WHERE abnormal)::bigint    AS n_abnormal,
  ROUND(100.0 * COUNT(*) FILTER (WHERE abnormal) / NULLIF(COUNT(*), 0), 2) AS abnormal_pct
FROM joined
GROUP BY district_code
HAVING COUNT(*) >= 5
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_{k}_screening
  ON public.mv_{k}_screening (district_code);

GRANT SELECT ON public.mv_{k}_screening
  TO bma_med_reader, bma_med_clinician, bma_med_loader,
     bma_etl_writer, bma_dba_admin, bma_api_reader;

COMMENT ON MATERIALIZED VIEW public.mv_{k}_screening IS
  '{K} screening abnormal rate per BKK district. n_abnormal/n_total. '
  'k-anon n>=5. Patients with NULL screening result excluded.';

REFRESH MATERIALIZED VIEW public.mv_{k}_screening;

-- =============================================================================
-- 2. mv_{k}_screening_region — non-BKK 4-region (N/NE/S/C)
-- =============================================================================
DROP MATERIALIZED VIEW IF EXISTS public.mv_{k}_screening_region CASCADE;

CREATE MATERIALIZED VIEW public.mv_{k}_screening_region AS
WITH
{_abnormal_cte(spec)},

patient_region AS (
  SELECT DISTINCT v.patient_id,
         CASE
           WHEN LEFT(v.home_district_code, 2)::int BETWEEN 50 AND 58 THEN 'N'
           WHEN LEFT(v.home_district_code, 2)::int BETWEEN 30 AND 49 THEN 'NE'
           WHEN LEFT(v.home_district_code, 2)::int BETWEEN 80 AND 96 THEN 'S'
           WHEN LEFT(v.home_district_code, 2)::int BETWEEN 11 AND 29 THEN 'C'
           WHEN LEFT(v.home_district_code, 2)::int BETWEEN 60 AND 77 THEN 'C'
           ELSE NULL
         END AS region_code
  FROM public.mv_visit_resolved v
  WHERE v.is_dedup_kept = TRUE
    AND v.home_district_code IS NOT NULL
    AND v.home_district_code ~ '^[0-9]{{4}}$'
),
joined AS (
  SELECT pr.region_code, pr.patient_id, pa.abnormal
  FROM patient_region pr
  JOIN patient_abnormal pa ON pa.patient_id = pr.patient_id
  WHERE pr.region_code IS NOT NULL
    AND pa.abnormal IS NOT NULL
)
SELECT
  region_code,
  CASE region_code
    WHEN 'N'  THEN 'ภาคเหนือ'
    WHEN 'NE' THEN 'ภาคอีสาน'
    WHEN 'S'  THEN 'ภาคใต้'
    WHEN 'C'  THEN 'ภาคกลาง'
  END AS region_name_th,
  COUNT(*)::bigint                            AS n_total,
  COUNT(*) FILTER (WHERE abnormal)::bigint    AS n_abnormal,
  ROUND(100.0 * COUNT(*) FILTER (WHERE abnormal) / NULLIF(COUNT(*), 0), 2) AS abnormal_pct
FROM joined
GROUP BY region_code
HAVING COUNT(*) >= 5
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_{k}_screening_region
  ON public.mv_{k}_screening_region (region_code);

GRANT SELECT ON public.mv_{k}_screening_region
  TO bma_med_reader, bma_med_clinician, bma_med_loader,
     bma_etl_writer, bma_dba_admin, bma_api_reader;

COMMENT ON MATERIALIZED VIEW public.mv_{k}_screening_region IS
  '{K} screening abnormal rate per non-BKK region. Same semantics as '
  'mv_{k}_screening. k-anon n>=5.';

REFRESH MATERIALIZED VIEW public.mv_{k}_screening_region;

COMMIT;

-- =============================================================================
-- END migration {n}
-- =============================================================================
"""
