"""FastAPI router generator for screening-only diseases.

Emits api/routers/<key>.py with two endpoints:
  GET /api/v2/<key>/screening?scope=zone|city|district|non_bkk
  GET /api/v2/<key>/screening/factors/bulk

The first returns:
  { scope, scope_id, n_total, n_abnormal, abnormal_pct, districts: [...] }

The second returns demographic / lifestyle factor cross-tabs at city,
zone, and district scope — same shape as NCD /factors/bulk but keyed by
abnormal_pct. Powers the tooltip's "ปัจจัยเด่น" panel.
"""
from __future__ import annotations

from ..diseases import ScreeningSpec
from .screening_factors_router import gen_screening_factors_endpoint


def gen_screening_router(spec: ScreeningSpec) -> str:
    k = spec.key
    K = spec.short_upper

    return f'''"""{K} screening router — exposes mv_{k}_screening.

Auto-generated by scaffold/scaffold.py from scaffold/diseases.py.
DO NOT hand-edit — re-run the scaffolder instead.
"""
from __future__ import annotations

import re
from typing import Optional

from fastapi import APIRouter, HTTPException, Query

from database import execute_query
from security import K_ANONYMITY_THRESHOLD
from cache import cache_get, cache_set, TTL_T3_FILTERED

router = APIRouter(prefix="/api/v2/{k}", tags=["{K} Screening"])

_VALID_SCOPES = {{"city", "zone", "district", "non_bkk"}}


@router.get("/screening")
def {k}_screening(
    scope: str = Query(..., description="zone | city | district | non_bkk"),
    id: Optional[str] = Query(None),
):
    """Aggregated abnormal-screening rate for {K}."""
    if scope not in _VALID_SCOPES:
        raise HTTPException(status_code=400, detail=f"Invalid scope")
    if scope == "zone" and not id:
        raise HTTPException(status_code=422, detail="id required for scope='zone'")
    if scope == "district":
        if not id:
            raise HTTPException(status_code=422, detail="id required for scope='district'")
        if not re.match(r"^10[0-9]{{2}}$", id):
            raise HTTPException(status_code=422, detail="district id must match ^10\\\\d\\\\d$")

    scope_id = id if scope not in ("city", "non_bkk") else None
    cache_key = f"{k}:screening:{{scope}}:{{scope_id}}"
    cached = cache_get(cache_key)
    if cached is not None:
        return cached

    if scope == "zone":
        rows = execute_query(
            """
            SELECT m.district_code, m.n_total, m.n_abnormal,
                   d.zone_code, d.name_th
            FROM public.mv_{k}_screening m
            LEFT JOIN public.ref_districts d ON d.dcode = m.district_code
            WHERE d.zone_code = %s
            """,
            (scope_id,),
        )
    elif scope == "district":
        rows = execute_query(
            """
            SELECT m.district_code, m.n_total, m.n_abnormal, NULL AS zone_code, NULL AS name_th
            FROM public.mv_{k}_screening m
            WHERE m.district_code = %s
            """,
            (scope_id,),
        )
    elif scope == "non_bkk":
        rows = execute_query(
            """SELECT region_code AS district_code, n_total, n_abnormal,
                      NULL AS zone_code, region_name_th AS name_th
               FROM public.mv_{k}_screening_region""",
            None,
        )
    else:  # city
        rows = execute_query(
            """SELECT m.district_code, m.n_total, m.n_abnormal, d.zone_code, d.name_th
               FROM public.mv_{k}_screening m
               LEFT JOIN public.ref_districts d ON d.dcode = m.district_code""",
            None,
        )

    if not rows:
        raise HTTPException(status_code=404, detail=f"No rows for scope='{{scope}}', id='{{scope_id}}'")

    n_total = sum(int(r["n_total"]) for r in rows)
    n_abnormal = sum(int(r["n_abnormal"]) for r in rows)
    if n_total < K_ANONYMITY_THRESHOLD:
        raise HTTPException(status_code=404, detail=f"Suppressed: total < {{K_ANONYMITY_THRESHOLD}}")

    districts_payload = [
        {{
            "district_code": r["district_code"],
            "district_name": r.get("name_th"),
            "zone_code": r.get("zone_code"),
            "n_total":    int(r["n_total"]),
            "n_abnormal": int(r["n_abnormal"]),
            "abnormal_pct": round(100.0 * int(r["n_abnormal"]) / int(r["n_total"]), 2)
                if int(r["n_total"]) > 0 else 0.0,
        }}
        for r in rows if int(r["n_total"]) >= K_ANONYMITY_THRESHOLD
    ]
    districts_payload.sort(key=lambda v: v["district_code"])

    result = {{
        "data": {{
            "scope": scope,
            "scope_id": scope_id,
            "n_total":    n_total,
            "n_abnormal": n_abnormal,
            "abnormal_pct": round(100.0 * n_abnormal / n_total, 2) if n_total > 0 else 0.0,
            "districts": districts_payload,
        }}
    }}

    cache_set(cache_key, result, TTL_T3_FILTERED)
    return result
''' + gen_screening_factors_endpoint(spec)
