"""Generator for mv_summary_global — the citywide 1-row KPI rollup that
powers the OverviewBoard's left panel (`/api/v2/summary/overview`).

Auto-emitted from the disease registry so adding a disease via the
scaffolder also propagates it into the OverviewBoard. Each disease
contributes one column whose value is COUNT(DISTINCT patient_id with
at-risk flag) for that disease.

NCD pipeline diseases use the convention:
  • diabetes / hypertension / cardiovascular  → risk_<key> on mv_visit_resolved
  • obesity / dyslipidemia                    → found_<key>  (measured)
  • Future NCDs scaffolded onto the 4-axis pipeline: any_<key>_signal
    derived from the per-district mv_<key>_classification.

Screening pipeline diseases plug into the same row by reading the
abnormal flag from `mv_<key>_screening` (district-level) and summing.

For now we keep the existing 5 entries (DM/HPT/CVD/obesity/lipid) hard-
coded into the SQL because they map 1:1 to columns on `mv_visit_resolved`;
adding more requires changing the source projection. The screening MVs
are aggregated separately by the API endpoint, not this MV.
"""
from __future__ import annotations

from ..diseases import DISEASES, SCREENING


# Column-source map for diseases whose at-risk count comes directly from
# mv_visit_resolved. Edit here (not the SQL) when adding NCDs.
#
# NOTE: cardiovascular was previously sourced from `risk_cvd` (WHO 10-yr risk).
# Per the official guideline (medical-knowledge/disease-criteria-guideline.jpg),
# CVD criterion is "EKG abnormal" — a screening test, NOT a risk score. CVD is
# now in SCREENING and its count comes from `mv_cvd_screening` via the
# overview router's screening branch.
_VISIT_FLAG: dict[str, str] = {
    "diabetes":     "risk_dm",
    "hypertension": "risk_hpt",
    "obesity":      "found_obesity",   # measured BMI ≥ 23 (NHES) — NOT risk_bmi
    "dyslipidemia": "found_dyslipidemia",
}


def gen_summary_global_sql() -> str:
    """Emit the full DROP + CREATE for mv_summary_global."""
    # Keep diseases in canonical display order. Skip any not in _VISIT_FLAG —
    # those need a different aggregation strategy (e.g. union of screening MVs).
    disease_keys = list(_VISIT_FLAG.keys())

    bucketed_cols  = ", ".join(_VISIT_FLAG[k] for k in disease_keys)
    flags_aliases  = ",\n    ".join(
        f"bool_or({_VISIT_FLAG[k]})       AS has_{_VISIT_FLAG[k]}"
        for k in disease_keys
    )
    final_cols = ",\n  ".join(
        f"COUNT(DISTINCT f.patient_id) FILTER (WHERE f.has_{_VISIT_FLAG[k]}) AS {k}"
        for k in disease_keys
    )

    return f"""-- =============================================================================
-- mv_summary_global — citywide 1-row KPI for OverviewBoard
-- =============================================================================
-- Auto-generated by scaffold/templates/summary_global.py.
-- DO NOT hand-edit. Edit `_VISIT_FLAG` in that file and re-emit.
-- =============================================================================

DROP MATERIALIZED VIEW IF EXISTS public.mv_summary_global CASCADE;

CREATE MATERIALIZED VIEW public.mv_summary_global AS
WITH bucketed AS (
  SELECT
    patient_id,
    is_dedup_kept,
    {bucketed_cols},
    CASE
      WHEN home_district_code BETWEEN '1001' AND '1050' THEN 'bkk'
      WHEN home_district_code IS NULL                   THEN 'unknown'
      ELSE                                                   'non_bkk'
    END AS bucket
  FROM public.mv_visit_resolved
  WHERE cancel_status IS DISTINCT FROM 1
),
flags AS (
  SELECT patient_id, bucket,
    {flags_aliases}
  FROM bucketed
  GROUP BY patient_id, bucket
),
visits AS (
  SELECT bucket, COUNT(*) AS n
  FROM bucketed
  WHERE is_dedup_kept = TRUE
  GROUP BY bucket
)
SELECT
  COUNT(DISTINCT f.patient_id)                                         AS total_screened,
  (SELECT COALESCE(SUM(n), 0) FROM visits)                             AS total_visits,
  COUNT(DISTINCT f.patient_id) FILTER (WHERE f.bucket='bkk')           AS bkk_screened,
  (SELECT COALESCE(n, 0) FROM visits WHERE bucket='bkk')               AS bkk_visits,
  COUNT(DISTINCT f.patient_id) FILTER (WHERE f.bucket='non_bkk')       AS non_bkk_screened,
  (SELECT COALESCE(n, 0) FROM visits WHERE bucket='non_bkk')           AS non_bkk_visits,
  COUNT(DISTINCT f.patient_id) FILTER (WHERE f.bucket='unknown')       AS unknown_screened,
  (SELECT COALESCE(n, 0) FROM visits WHERE bucket='unknown')           AS unknown_visits,
  {final_cols},
  NOW()                                                                AS refreshed_at
FROM flags f
WITH NO DATA;

CREATE UNIQUE INDEX uq_mv_summary_global
  ON public.mv_summary_global (refreshed_at);

GRANT SELECT ON public.mv_summary_global
  TO bma_med_reader, bma_med_clinician, bma_med_loader,
     bma_etl_writer, bma_dba_admin, bma_api_reader;

COMMENT ON MATERIALIZED VIEW public.mv_summary_global IS
  'Citywide 1-row KPI with bkk/non_bkk/unknown bucket breakdown. '
  'Auto-generated from scaffold/templates/summary_global.py. Disease '
  'columns mirror _VISIT_FLAG in that template.';

REFRESH MATERIALIZED VIEW public.mv_summary_global;
"""


def disease_keys_for_overview() -> list[str]:
    """List of disease keys exposed by the API's `by_disease` array.
    Used by api/routers/summary.py to iterate consistently with the MV."""
    return list(_VISIT_FLAG.keys())


def screening_keys_for_overview() -> list[str]:
    """Screening-pipeline disease keys — exposed in `by_disease` via a
    separate query against mv_<key>_screening."""
    return list(SCREENING.keys())
