"""ANEMIA screening router — exposes mv_anemia_screening.

Auto-generated by scaffold/scaffold.py from scaffold/diseases.py.
DO NOT hand-edit — re-run the scaffolder instead.
"""
from __future__ import annotations

import re
from typing import Optional

from fastapi import APIRouter, HTTPException, Query

from database import execute_query
from security import K_ANONYMITY_THRESHOLD
from cache import cache_get, cache_set, TTL_T3_FILTERED

router = APIRouter(prefix="/api/v2/anemia", tags=["ANEMIA Screening"])

_VALID_SCOPES = {"city", "zone", "district", "non_bkk"}


@router.get("/screening")
def anemia_screening(
    scope: str = Query(..., description="zone | city | district | non_bkk"),
    id: Optional[str] = Query(None),
):
    """Aggregated abnormal-screening rate for ANEMIA."""
    if scope not in _VALID_SCOPES:
        raise HTTPException(status_code=400, detail=f"Invalid scope")
    if scope == "zone" and not id:
        raise HTTPException(status_code=422, detail="id required for scope='zone'")
    if scope == "district":
        if not id:
            raise HTTPException(status_code=422, detail="id required for scope='district'")
        if not re.match(r"^10[0-9]{2}$", id):
            raise HTTPException(status_code=422, detail="district id must match ^10\\d\\d$")

    scope_id = id if scope not in ("city", "non_bkk") else None
    cache_key = f"anemia:screening:{scope}:{scope_id}:s"
    cached = cache_get(cache_key)
    if cached is not None:
        return cached

    if scope == "zone":
        rows = execute_query(
            """
            SELECT m.district_code, m.n_total, m.n_abnormal,
                   d.zone_code, d.name_th
            FROM public.mv_anemia_screening m
            LEFT JOIN public.ref_districts d ON d.dcode = m.district_code
            WHERE d.zone_code = %s
            """,
            (scope_id,),
        )
    elif scope == "district":
        rows = execute_query(
            """
            SELECT m.district_code, m.n_total, m.n_abnormal, NULL AS zone_code, NULL AS name_th
            FROM public.mv_anemia_screening m
            WHERE m.district_code = %s
            """,
            (scope_id,),
        )
    elif scope == "non_bkk":
        rows = execute_query(
            """SELECT region_code AS district_code, n_total, n_abnormal,
                      NULL AS zone_code, region_name_th AS name_th
               FROM public.mv_anemia_screening_region""",
            None,
        )
    else:  # city
        rows = execute_query(
            """SELECT m.district_code, m.n_total, m.n_abnormal, d.zone_code, d.name_th
               FROM public.mv_anemia_screening m
               LEFT JOIN public.ref_districts d ON d.dcode = m.district_code""",
            None,
        )

    if not rows:
        raise HTTPException(status_code=404, detail=f"No rows for scope='{scope}', id='{scope_id}'")

    n_total = sum(int(r["n_total"]) for r in rows)
    n_abnormal = sum(int(r["n_abnormal"]) for r in rows)
    if n_total < K_ANONYMITY_THRESHOLD:
        raise HTTPException(status_code=404, detail=f"Suppressed: total < {K_ANONYMITY_THRESHOLD}")

    districts_payload = [
        {
            "district_code": r["district_code"],
            "district_name": r.get("name_th"),
            "zone_code": r.get("zone_code"),
            "n_total":    int(r["n_total"]),
            "n_abnormal": int(r["n_abnormal"]),
            "abnormal_pct": round(100.0 * int(r["n_abnormal"]) / int(r["n_total"]), 2)
                if int(r["n_total"]) > 0 else 0.0,
        }
        for r in rows if int(r["n_total"]) >= K_ANONYMITY_THRESHOLD
    ]
    districts_payload.sort(key=lambda v: v["district_code"])

    # Per-subdistrict ranking (only for scope='district') from mv_anemia_subdistrict.
    subdistricts_payload: list[dict] = []
    if scope == "district" and scope_id:
        sub_rows = execute_query(
            """
            SELECT subdistrict_code, n_total::bigint AS n_total,
                   n_signal::bigint AS n_signal, signal_pct
            FROM public.mv_anemia_subdistrict
            WHERE district_code = %s
            ORDER BY signal_pct DESC
            """,
            (scope_id,),
        )
        subdistricts_payload = [
            {
                "subdistrict_code": r["subdistrict_code"],
                "n_total":      int(r["n_total"]),
                "n_abnormal":   int(r["n_signal"]),
                "abnormal_pct": float(r["signal_pct"] or 0),
            }
            for r in sub_rows
        ]

    result = {
        "data": {
            "scope": scope,
            "scope_id": scope_id,
            "n_total":    n_total,
            "n_abnormal": n_abnormal,
            "abnormal_pct": round(100.0 * n_abnormal / n_total, 2) if n_total > 0 else 0.0,
            "districts": districts_payload,
            "subdistricts": subdistricts_payload,
        }
    }

    cache_set(cache_key, result, TTL_T3_FILTERED)
    return result

# =============================================================================
# /screening/factors/bulk — demographic/lifestyle factor cross-tab (mig 352)
# =============================================================================

# Display labels for the 5 factors. Group-level labels live inline on each
# MV row (factor_group_th / factor_group_en), so we only carry header
# labels here.
_ANEMIA_FACTOR_LABELS: dict[str, dict[str, str]] = {
    "sex":       {"th": "เพศ",                    "en": "Sex"},
    "age_group": {"th": "กลุ่มอายุ",               "en": "Age group"},
    "smoke":     {"th": "การสูบบุหรี่",             "en": "Smoking status"},
    "alcohol":   {"th": "การดื่มแอลกอฮอล์",         "en": "Alcohol consumption"},
    "excercise": {"th": "การออกกำลังกาย",          "en": "Exercise frequency"},
}

# Stable display order within each factor (ordinal, not by lift).
_ANEMIA_GROUP_ORDER: dict[str, list[str]] = {
    "sex":       ["male", "female"],
    "age_group": ["18-29", "30-44", "45-59", "60-74", "75+"],
    "smoke":     ["non_smoker", "former_smoker", "current_smoker"],
    "alcohol":   ["non_drinker", "former_drinker", "current_drinker"],
    "excercise": ["regular", "sometimes", "never"],
}


def _shape_anemia_screening_factors(rows: list[dict], scope: str, scope_id: object) -> dict:
    """Reshape raw MV rows into the canonical screening-factors response.

    Lift baseline: the scope-level abnormal_pct using the factor with
    largest coverage (n_total) — typically `sex` (~99% coverage).
    """
    factor_totals: dict[str, tuple[int, int]] = {}
    for r in rows:
        fk = r["factor_key"]
        n_acc, abn_acc = factor_totals.get(fk, (0, 0))
        factor_totals[fk] = (n_acc + int(r["n_total"]), abn_acc + int(r["n_abnormal"]))
    if not factor_totals:
        return {
            "scope":             scope,
            "scope_id":          scope_id,
            "area_abnormal_pct": 0.0,
            "factors":           [],
        }
    baseline_fk = max(factor_totals, key=lambda k: factor_totals[k][0])
    base_n, base_abn = factor_totals[baseline_fk]
    area_pct = round(100.0 * base_abn / base_n, 2) if base_n > 0 else 0.0

    by_factor: dict[str, list[dict]] = {}
    for r in rows:
        fk = r["factor_key"]
        n_total = int(r["n_total"])
        n_abnormal = int(r["n_abnormal"])
        abn_pct = round(100.0 * n_abnormal / n_total, 2) if n_total > 0 else 0.0
        lift = round(abn_pct / area_pct, 2) if area_pct > 0 else 0.0
        by_factor.setdefault(fk, []).append({
            "group":        r["factor_group"],
            "label_th":     r["factor_group_th"],
            "label_en":     r["factor_group_en"],
            "n_total":      n_total,
            "n_abnormal":   n_abnormal,
            "abnormal_pct": abn_pct,
            "lift":         lift,
        })

    factors_payload: list[dict] = []
    for fk in _ANEMIA_FACTOR_LABELS:
        groups = by_factor.get(fk, [])
        if not groups:
            continue
        order = {g: i for i, g in enumerate(_ANEMIA_GROUP_ORDER.get(fk, []))}
        groups.sort(key=lambda g: order.get(g["group"], 99))
        eligible = [g for g in groups if g["n_total"] >= K_ANONYMITY_THRESHOLD]
        top_group = max(eligible, key=lambda g: g["lift"])["group"] if eligible else None
        factors_payload.append({
            "factor_key":      fk,
            "factor_label_th": _ANEMIA_FACTOR_LABELS[fk]["th"],
            "factor_label_en": _ANEMIA_FACTOR_LABELS[fk]["en"],
            "groups":          groups,
            "top_group":       top_group,
        })

    return {
        "scope":             scope,
        "scope_id":          scope_id,
        "area_abnormal_pct": area_pct,
        "factors":           factors_payload,
    }


@router.get("/screening/factors/bulk")
def anemia_screening_factors_bulk():
    """One-shot: city + all zones + all districts of ANEMIA factor cross-tab.

    Cached aggressively under a single static key — payload is identical
    for every reader.
    """
    cache_key = "anemia:screening:factors:bulk"
    cached = cache_get(cache_key)
    if cached is not None:
        return cached

    rows = execute_query(
        """
        SELECT scope, scope_id, factor_key, factor_group,
               factor_group_th, factor_group_en,
               n_total::bigint AS n_total,
               n_abnormal::bigint AS n_abnormal
        FROM public.mv_anemia_screening_factors
        """,
        None,
    )

    by_zone: dict[str, list[dict]] = {}
    by_dist: dict[str, list[dict]] = {}
    city_rows: list[dict] = []
    for r in rows:
        if r["scope"] == "city":
            city_rows.append(r)
        elif r["scope"] == "zone":
            by_zone.setdefault(r["scope_id"], []).append(r)
        elif r["scope"] == "district":
            by_dist.setdefault(r["scope_id"], []).append(r)

    payload = {
        "data": {
            "city":      _shape_anemia_screening_factors(city_rows, "city", None),
            "zones":     {zc: _shape_anemia_screening_factors(rs, "zone", zc) for zc, rs in by_zone.items()},
            "districts": {dc: _shape_anemia_screening_factors(rs, "district", dc) for dc, rs in by_dist.items()},
        }
    }

    cache_set(cache_key, payload, TTL_T3_FILTERED)
    return payload
